# Generated by Django 5.2.6 on 2025-09-12 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('student_count', models.IntegerField(blank=True, null=True)),
                ('ranking_world', models.IntegerField(blank=True, null=True)),
                ('ranking_country', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'db_table': 'universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('field_of_study', models.CharField(max_length=200)),
                ('degree_level', models.CharField(choices=[('master', 'Master'), ('phd', 'PhD'), ('bachelor', 'Bachelor'), ('diploma', 'Diploma')], default='master', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_months', models.IntegerField(blank=True, help_text='Duration in months', null=True)),
                ('language', models.CharField(default='English', max_length=100)),
                ('tuition_fee_euro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('min_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('ielts_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('toefl_score', models.IntegerField(blank=True, null=True)),
                ('gre_score', models.IntegerField(blank=True, null=True)),
                ('program_website', models.URLField(blank=True, null=True)),
                ('brochure_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'db_table': 'programs',
                'ordering': ['university__name', 'name'],
                'unique_together': {('university', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('public_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('head', 'Head of Department'), ('coordinator', 'Program Coordinator'), ('advisor', 'Academic Advisor'), ('director', 'Program Director'), ('professor', 'Professor')], default='coordinator', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_location', models.CharField(blank=True, max_length=200, null=True)),
                ('office_hours', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='universities.program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='universities.university')),
            ],
            options={
                'db_table': 'coordinators',
                'ordering': ['university__name', 'program__name', 'name'],
                'unique_together': {('program', 'public_email')},
            },
        ),
    ]
