# Generated by Django 5.2.3 on 2025-09-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='university_id',
            field=models.CharField(default='TEMP_ID', help_text='Unique identifier for the university', max_length=20, unique=True),
        ),
    ]
