# Generated by Django 5.2.3 on 2025-09-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_university_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_id',
            field=models.CharField(default='TEMP_PROG_ID', help_text='Unique identifier for the program', max_length=20, unique=True),
        ),
    ]
